services:
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www/
        depends_on:
            -   app
        container_name: payments_app_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        depends_on:
            -   db
        container_name: payments_app

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: payments_app_db
